### Homework 1 - Question 6 - Luke Arend

Consider a linear system which transforms $\vec{v}$ to $\vec{y}$ such that $\vec{y} = M \vec{v}$.

### a)

The null space of the matrix M is the set of vectors which, when left-multiplied by M, result in the zero vector. It is the subspace of the input space which is completely discarded by the transform M.

The range space of the matrix M is the set of vectors reachable by applying M to any input vector. It is the subspace of the output space actually occupied by the transform M applied to all possible inputs.

### b)

Consider a creature which produces a neural response vector to a vector input of pressure measurements. If the system has a non-zero null space, then some pressure vectors are mapped to the zero vector. This means that there exist stimuli which, when presented to the animal, produce no neural response. Call these "null" stimuli.

Since the system is linear, any null stimulus could be added to any ordinary stimulus to produce a metamer: a second, different stimulus which, when presented to the animal, produces the same neural response as the original.

### c)

In [1]:
import numpy as np
import scipy

In [2]:
data = scipy.io.loadmat('Hw1Q6_MtxExamples.mat')

### M1

In [3]:
M1 = data['mtx1']
M1

array([[1.76371689, 0.18079736, 1.96484125],
       [0.68217653, 0.18724003, 0.64619217]])

In [4]:
U, S, Vt = np.linalg.svd(M1)
S

array([2.81131413, 0.13596668])

1)

Since there are 3 input dimensions and only 2 singular values, the third input dimension is discarded by the transform $M_1$. It is spanned by the third column of $V$.

Sample a random vector along the third column of $V$. Applying $M_1$ gives the zero vector.

In [5]:
v = Vt.T[:, 2] * np.random.randn()
np.dot(M1, v)

array([-2.06095361e-16, -4.60333619e-18])

2)

The range space of $M_1$ is spanned by the columns of $U$. Sample a random vector $\vec{y}$ from the range space.

In [6]:
y = np.dot(U.T, np.random.randn(2))
y

array([-0.70201609, -0.53103311])

If $\vec{y} = M \vec{x}$, then $\vec{x} = M^{-1} \vec{y}$. And since $M = U S V^T$, $M^{-1} = V S^{-1} U^T$. So $\vec{x} = V S^{-1} U^T \vec{y}$.

In [7]:
S_inv = np.diag(1 / S)
S_inv = np.concatenate([S_inv, [[0, 0]]], axis=0)
M_inv = np.dot(np.dot(Vt.T, S_inv), U.T)
x = np.dot(M_inv, y)
x

array([-0.86015132, -1.66152058,  0.56770279])

Verify that $\vec{y} = M \vec{x}$ for `x` and `y`.

In [8]:
np.allclose(y, np.dot(M1, x))

True

### M2

In [9]:
M2 = data['mtx2']
M2

array([[-0.19744334,  0.01215894, -0.58881013],
       [ 0.43287258, -0.02665713,  1.29090077],
       [ 1.07207807, -0.06602064,  3.19712192]])

In [10]:
U, S, Vt = np.linalg.svd(M2)
S

array([3.68993791e+00, 3.25816135e-16, 1.25679497e-18])

1)

$M_2$ has just one singular value. So the null space is spanned by the last two columns of $V$.

If we sample a vector from the null space and apply $M_2$, we get the zero vector.

In [11]:
v = np.dot(Vt.T[:, -2:], np.random.randn(2))
np.dot(M2, v)

array([ 1.41060538e-16, -2.97591557e-16, -6.86318549e-16])

2)

Since $M_2$ has one singular value, the first column of $U$ spans the range space. Sample a random vector $\vec{y}$ from the range space.

In [12]:
y = U[:, 0] * np.random.randn()
y

array([-0.1673523 ,  0.36690132,  0.90868972])

Find an $\vec{x}$ such that $\vec{y} = M_2 \vec{x}$.

In [13]:
S_inv = np.diag([1 / S[0], 0, 0])
M_inv = np.dot(np.dot(Vt.T, S_inv), U.T)
x = np.dot(M_inv, y)
x

array([ 0.0856405 , -0.00527391,  0.25539477])

In [14]:
np.allclose(y, np.dot(M2, x))

True

### M3

In [15]:
M3 = data['mtx3']
M3

array([[-0.52084555,  3.27506098],
       [ 0.75993107, -0.69773866],
       [-0.60979668, -4.31920227]])

In [16]:
U, S, Vt = np.linalg.svd(M3)
S

array([5.46570167, 1.1023178 ])

1)

Since there are 2 input dimensions and 2 singular values, the transform does not have a null space.

2)

Since there are 3 output dimensions and only 2 singular values, the range space is spanned by the first two columns of $U$.

We can sample a random vector $\vec{y}$ from the range space and solve for $\vec{x}$ such that $\vec{y} = M_3 \vec{x}$.

In [17]:
y = np.dot(U[:, :2], np.random.randn(2))
y

array([-0.53561024, -0.45220568,  1.83792154])

In [18]:
S_inv = np.diag(1 / S)
S_inv = np.concatenate([S_inv, [[0], [0]]], axis=1)
M_inv = np.dot(np.dot(Vt.T, S_inv), U.T)
x = np.dot(M_inv, y)
x

array([-0.87264112, -0.30232154])

In [19]:
np.allclose(y, np.dot(M3, x))

True

### M4

In [20]:
M4 = data['mtx4']
M4

array([[-0.095065  ,  0.7939639 ],
       [ 0.85959259,  0.27567482]])

In [21]:
U, S, Vt = np.linalg.svd(M4)
S

array([0.94338616, 0.75122208])

1)

Since there are 2 input dimensions and 2 singular values, the transform does not have a null space.

2)

Since there are 2 output dimensions and 2 singular values, the range space is the column space of U.

Sample a random vector $\vec{y}$ from the range space and solve for $\vec{x}$ such that $\vec{y} = M_3 \vec{x}$.

In [22]:
y = np.dot(U, np.random.randn(2))
y

array([ 0.6986013, -1.283732 ])

In [23]:
S_inv = np.diag(1 / S)
M_inv = np.dot(np.dot(Vt.T, S_inv), U.T)
x = np.dot(M_inv, y)
x

array([-1.7099428 ,  0.67515109])

In [24]:
np.allclose(y, np.dot(M4, x))

True

### M5

In [25]:
M5 = data['mtx5']
M5

array([[-3.44738961, -5.50282864],
       [-3.19713133, -5.10335872]])

In [26]:
U, S, Vt = np.linalg.svd(M5)
S

array([8.85615815e+00, 2.40750870e-16])

1)

The input space has 2 dimensions and there is just one singular value, so the second column of $V$ spans the null space.

If we sample a random vector from the null space and apply $M_5$, we get the zero vector.

In [27]:
v = Vt.T[:, 1] * np.random.randn()
np.dot(M5, v)

array([1.49850853e-15, 1.05727513e-15])

2)

Since the output space has 2 dimensions and there is one singular value, the first column of U spans the range space.

Sample a vector $\vec{y}$ from the range space and solve for $\vec{x}$ such that $\vec{y} = M_3 \vec{x}$.

In [28]:
y = np.dot(U[:, 0], np.random.randn())
y

array([0.80923837, 0.75049288])

In [29]:
S_inv = np.diag([1 / S[0], 0])
M_inv = np.dot(np.dot(Vt.T, S_inv), U.T)
x = np.dot(M_inv, y)
x

array([-0.06616196, -0.10560974])

In [30]:
np.allclose(y, np.dot(M5, x))

True